[package]
name = "ssh-browser"
version = "0.1.0"
edition = "2021"


[dependencies]
ssh2 = "0.9.4"
eframe = "0.29.1"
rfd = "0.15.1"
libc = "0.2.168"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
